#!/usr/bin/env python3
"""Synchronize the gitgraph runtime into the Claude Code plugin and the Codex package.

The canonical runtime is gitgraph/runtime/gitgraph.py. The Claude Code plugin carries it as a
string in gitgraph/hooks/runtime.ts (its hooks module writes it out and runs it); the Codex
package carries a copy at plugins/gitgraph/scripts/gitgraph.py.
"""

import argparse
import json
from pathlib import Path
import shutil
import stat
import sys

HEADER = "// Generated by scripts/sync-gitgraph.py from gitgraph/runtime/gitgraph.py: edit that file, then run the script.\n"


def generated_module(source):
    return HEADER + "export const RUNTIME_SOURCE = " + json.dumps(source.decode("utf-8")) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report drift without writing files.")
    arguments = parser.parse_args()
    repository = Path(__file__).resolve().parents[1]
    source = repository / "gitgraph/runtime/gitgraph.py"
    module = repository / "gitgraph/hooks/runtime.ts"
    copy = repository / "plugins/gitgraph/scripts/gitgraph.py"

    if not source.is_file() or source.is_symlink():
        print(f"Canonical runtime is missing or is a symlink: {source}", file=sys.stderr)
        return 1
    for destination in (module, copy):
        if destination.is_symlink():
            print(f"Synchronized files must not be symlinks: {destination}", file=sys.stderr)
            return 1

    contents = source.read_bytes()
    mode = stat.S_IMODE(source.stat().st_mode)
    expected = generated_module(contents).encode("utf-8")
    is_module_current = module.is_file() and module.read_bytes() == expected
    is_copy_current = (
        copy.is_file() and copy.read_bytes() == contents and stat.S_IMODE(copy.stat().st_mode) == mode
    )
    if is_module_current and is_copy_current:
        print("gitgraph runtime is synchronized.")
        return 0
    if arguments.check:
        print("gitgraph runtime copies are missing or stale; run scripts/sync-gitgraph.py.", file=sys.stderr)
        return 1

    if not is_module_current:
        module.write_bytes(expected)
        print("Synchronized gitgraph/hooks/runtime.ts.")
    if not is_copy_current:
        copy.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, copy)
        copy.chmod(mode)
        print("Synchronized plugins/gitgraph/scripts/gitgraph.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
